package com.yzf.king.kit;

/**
 * ClaseName：ResultCode
 * Description：
 * Author：JensenWei
 * QQ: 2188307188
 * Createtime：2018/1/25 13:54
 * Modified By：
 * Fixtime：2018/1/25 13:54
 * FixDescription：
 */

/**
 * 响应码枚举，参考HTTP状态码的语义
 */
public enum Version {
    REGISTER(AppConfig.REGISTER, "1.0"),
    MODIFYPWD(AppConfig.MODIFYPWD, "1.0"),
    GETSMSCODE(AppConfig.GETSMSCODE, "1.0"),
    CARDOPERATE(AppConfig.CARDOPERATE, "1.0"),
    UPLOADFILE(AppConfig.UPLOADFILE, "1.0"),
    FORGOTPWD(AppConfig.FORGOTPWD, "1.0"),
    FACEMATCH(AppConfig.FACEMATCH, "1.0"),
    WITHDRAW(AppConfig.WITHDRAW, "1.1"),
    QUICKPAYAPPLY(AppConfig.QUICKPAYAPPLY, "1.0"),
    QUICKPAY(AppConfig.QUICKPAY, "1.0"),
    GETTRADEABILITY(AppConfig.GETTRADEABILITY, "1.0"),
    OPENTRANS(AppConfig.OPENTRANS, "1.0"),
    PLANOPERATOR(AppConfig.PLANOPERATOR, "1.0"),
    LOGIN(AppConfig.LOGIN, "1.1"),
    GETFEEINFO(AppConfig.GETFEEINFO, "1.0"),
    GETCARDINFO(AppConfig.GETCARDINFO, "1.0"),
    GETACCTINFO(AppConfig.GETACCTINFO, "1.1"),
    GETMERCHINFO(AppConfig.GETMERCHINFO, "1.0"),
    GETPUSHMSG(AppConfig.GETPUSHMSG, "1.0"),
    UPDATEPUSHMSG(AppConfig.UPDATEPUSHMSG, "1.0"),
    UPDATENOTICE(AppConfig.UPDATENOTICE, "1.0"),
    GETNOTICE(AppConfig.GETNOTICE, "1.0"),
    GETSUBMERCHINFO(AppConfig.GETSUBMERCHINFO, "1.0"),
    GETSUBMERCHCOUNT(AppConfig.GETSUBMERCHCOUNT, "1.0"),
    GETSUBMERCHDETAIL(AppConfig.GETSUBMERCHDETAIL, "1.0"),
    GETTRANSDTL(AppConfig.GETTRANSDTL, "1.0"),
    GETTRANSDAILY(AppConfig.GETTRANSDAILY, "1.0"),
    GETPROFITDAILY(AppConfig.GETPROFITDAILY, "1.0"),
    GETLOCATIONINFO(AppConfig.GETLOCATIONINFO, "1.0"),
    CHECKAPPVERSION(AppConfig.CHECKAPPVERSION, "1.0"),
    GETURL(AppConfig.GETURL, "1.0"),
    GETPLANCHANNELINFO(AppConfig.GETPLANCHANNELINFO, "1.0"),
    GETPLANINFO(AppConfig.GETPLANINFO, "1.0"),
    MERCHINCOME(AppConfig.MERCHINCOME, "1.0"),
    GETAUTHINCOMEINFO(AppConfig.GETAUTHINCOMEINFO, "1.0"),
    INCOMEBINDCARD(AppConfig.INCOMEBINDCARD, "1.0"),
    REFRESH(AppConfig.REFRESH, "1.1"),
    GETSHAREIMG(AppConfig.GETSHAREIMG, "1.0"),
    GETMERCHPHOTOS(AppConfig.GETMERCHPHOTOS, "1.0"),
    GETTEAMINFO(AppConfig.GETTEAMINFO, "1.0"),
    GETPUSHMSGCOUNT(AppConfig.GETPUSHMSGCOUNT, "1.0"),
    GETHELPINFO(AppConfig.GETHELPINFO, "1.0"),

    GETPOSKEY(AppConfig.GETPOSKEY, "1.0"),
    POSPAYAPPLY(AppConfig.POSPAYAPPLY, "1.0"),
    POSPAYCONFIRM(AppConfig.POSPAYCONFIRM, "1.0"),
    GETMPOSCHANNELMERCHINFO(AppConfig.GETMPOSCHANNELMERCHINFO, "1.0"),
    GETMPOSINCOMERESULT(AppConfig.GETMPOSINCOMERESULT, "1.0"),
    GETPOSCHANLFEE(AppConfig.GETPOSCHANLFEE, "1.0"),
    GETCHANNELINFO(AppConfig.GETCHANNELINFO, "1.0"),
    GETPLANDTL(AppConfig.GETPLANDTL, "2.0"),
    RANDOM(AppConfig.RANDOM, "1.0"),
    CREATE(AppConfig.CREATE, "1.0"),
    CONFIRM(AppConfig.CONFIRM, "1.0"),
    GETCREDITINFO(AppConfig.GETCREDITINFO, "1.0"),
    GETPROCESSPLAN(AppConfig.GETPROCESSPLAN, "1.0"),
    GETAUTHINFO(AppConfig.GETAUTHINFO, "1.0"),
    UPLOADCONTACT(AppConfig.UPLOADCONTACT, "1.0"),
    GETMAILBILL(AppConfig.GETMAILBILL, "1.0"),

    PARTNERLOGIN(AppConfig.PARTNERLOGIN, "1.0"),
    COUNTACCTINFO(AppConfig.COUNTACCTINFO, "1.0"),
    COUNTTEAMINFO(AppConfig.COUNTTEAMINFO, "1.0"),
    COUNTTRANSINFO(AppConfig.COUNTTRANSINFO, "1.0"),
    GETTRANSINFOCOUNT(AppConfig.GETTRANSINFOCOUNT, "1.0"),
    GETTRANSINFOCOUNTDTL(AppConfig.GETTRANSINFOCOUNTDTL, "1.0"),
    GETTEAMINFOCOUNT(AppConfig.GETTEAMINFOCOUNT, "1.0"),
    GETTEAMINFOCOUNTDTL(AppConfig.GETTEAMINFOCOUNTDTL, "1.0"),
    GETMYTERMINFO(AppConfig.GETMYTERMINFO, "1.0"),
    GETGOODSINFO(AppConfig.GETGOODSINFO, "1.0"),
    GETTMACHINAPPLYINFO(AppConfig.GETTMACHINAPPLYINFO, "1.0"),
    GETTEAMTERMINFO(AppConfig.GETTEAMTERMINFO, "1.0"),
    GETTMACHINAPPLYINFODTL(AppConfig.GETTMACHINAPPLYINFODTL, "1.0"),
    LOOTSHOP(AppConfig.LOOTSHOP, "1.0"),
    GETTRANSDEVICES(AppConfig.GETTRANSDEVICES, "1.0"),
    SHOPCONFIRM(AppConfig.SHOPCONFIRM, "1.0"),
    GETTERMINFO(AppConfig.GETTERMINFO, "1.0"),
    GETSHOPINFO(AppConfig.GETSHOPINFO, "1.0"),
    GETSPREADSHOPINFO(AppConfig.GETSPREADSHOPINFO, "1.0"),
    GETSHOPINFODTLINFO(AppConfig.GETSHOPINFODTLINFO, "1.0"),
    GETBENEFITDAILY(AppConfig.GETBENEFITDAILY, "1.1"),
    INSTALLCONFIRM(AppConfig.INSTALLCONFIRM, "1.0"),
    GETBENEFITDTL(AppConfig.GETBENEFITDTL, "1.1"),
    GETSHOPAROUND(AppConfig.GETSHOPAROUND, "1.0"),
    GETTRANSTERMINFO(AppConfig.GETTRANSTERMINFO, "1.0"),
    GETSUNMERCHINFOLIST(AppConfig.GETSUNMERCHINFOLIST, "1.0"),
    ADDSHOPINFO(AppConfig.ADDSHOPINFO, "1.0"),
    SHOPAPPLY(AppConfig.SHOPAPPLY, "1.0"),
    ADDAPPLYINFO(AppConfig.ADDAPPLYINFO, "1.0"),
    GETORDERSDAILY(AppConfig.GETORDERSDAILY, "1.0"),
    GETORDERSDTL(AppConfig.GETORDERSDTL, "1.0"),
    GETRECOMMENDSHOP(AppConfig.GETRECOMMENDSHOP, "1.0"),
    GETAGENTINFO(AppConfig.GETAGENTINFO, "1.0"),

    KAYOUINCOME(AppConfig.KAYOUINCOME, "1.0"),
    ADDRESSOPERA(AppConfig.ADDRESSOPERA, "1.0"),
    GETKAYOUINCOMERESULT(AppConfig.GETKAYOUINCOMERESULT, "1.0"),
    GETMPOSAPPLYRECORD(AppConfig.GETMPOSAPPLYRECORD, "1.0"),
    GETKAYOUCHANLFEE(AppConfig.GETKAYOUCHANLFEE, "1.0"),
    RECEIPT(AppConfig.RECEIPT, "1.0"),
    MPOSPAY(AppConfig.MPOSPAY, "1.0");



    private String url;
    private String version;

    Version(String url, String version) {
        this.url = url;
        this.version = version;
    }

    public String url() {
        return url;
    }

    public String version() {
        return version;
    }
}